package sinc2.rule;

import java.util.ArrayList;
import java.util.List;

/**
 * This class is for a batch of evidence generated by a single rule. The structure of evidence looks like this:
 *
 *          Rel1    Rel2    ...     Reln
 *  Ev1     rec11   rec12   ...     rec1n
 *  Ev2     rec21   rec22   ...     rec2n
 *  ...
 *  Evk     reck1   reck2   ...     reckn
 *
 * @since 2.0
 */
public class EvidenceBatch {
    /** The relation of each predicate in the rule */
    public final int[] relationsInRule;
    /** The list of evidence. Each list is a piece of evidence */
    public final List<int[][]> evidenceList = new ArrayList<>();

    public EvidenceBatch(int[] relationsInRule) {
        this.relationsInRule = relationsInRule;
    }
}
